# PyTorch Basics
## Dec 6, 2020

In [1]:
import numpy as np
import torch

In [2]:
# at its core, pyTorch is a library for processing tensors. A tensor is a number, vector, matrix or any n-dimensional array. Eg:
t1 = torch.tensor(4.)
t1.dtype

torch.float32

In [3]:
#vector
t2 = torch.tensor([1,2,3,4])
t2

tensor([1, 2, 3, 4])

In [4]:
#Matrix
t3 = torch.tensor([[5,6], [7,8], [9,10]])
t3

tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [5]:
# 3 dimensional tensor
t4 = torch.tensor([
    [[11, 12, 13],
    [13,14,15]],
    [[16,17,18],
    [19,20,21]]])
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[16, 17, 18],
         [19, 20, 21]]])

In [6]:
# NOTE: Tensors must have a regular shape, we cannot add a column to an arbritary row
print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t4.shape)

torch.Size([])
torch.Size([4])
torch.Size([3, 2])
torch.Size([2, 2, 3])


In [7]:
# Tensor operations
# We can combine tensors with the usual arithmetic operations 
x=torch.tensor(3.)
w=torch.tensor(4., requires_grad=True)
b=torch.tensor(5., requires_grad=True)

In [8]:
# we created x,w, and b, all numbers. We can combined as folows: 
y = w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [9]:
# As exected, y = 17
# What makes pytorch special? We can auotmaically compute the derivative of y w.r.t to the tensors that ahve required_grad = true. To compute these derivaties, we can call `.backwards`
y.backward()

In [10]:
#display gradients
print('dy/dx: ', x.grad)
print('dy/dw: ', w.grad)
print('dy/db: ', b.grad)


dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


In [11]:
# grad stands for graident, which is another term of derivative used mainly in dealing with matrices

# Using Numpy

In [12]:
# PyTorch interoperates very will with Numpy. 

x = np.array([[1,2], [3,4]])
x

array([[1, 2],
       [3, 4]])

In [13]:
y = torch.from_numpy(x) #maintains reference to np array

In [14]:
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [15]:
z = torch.tensor(x) # creates copy

In [16]:
z

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [17]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])